<?php
include("php_includes/mysqli_connect.php");

$amountDue = "";
//Get the total minutes for all the broadcast from the provider
$sql = "SELECT id FROM audio_stats WHERE username=:username";
$stmt = $db_connect->prepare($sql);
$stmt->bindParam(':username', $u, PDO::PARAM_STR);
$stmt->execute();

$requestCount = $stmt->rowCount();

$amountDue = $requestCount * 20; // multiply request count by 20 naira(forty percent of 50 naira. 50 naira is the cost per minute of audio broadcast)
//echo $totalmin;
//$terminated = "TERMINATED";
$sql_statement = "SELECT dates, mobile, talk, statusCode FROM audio_stats WHERE audio_id=:id AND audio_tag=:tag ORDER BY dates DESC";
$stmt = $db_connect->prepare($sql_statement);
$stmt->bindParam(':id', $id, PDO::PARAM_STR);
$stmt->bindParam(':tag', $tag, PDO::PARAM_STR);
$stmt->execute();

$count = $stmt->rowCount();
//initialize the variable
$totalGenerated = "";
//calculate total generated by this broadcast
$totalGenerated = $count * 20;

// Specify how many result per page
$rpp = '20';
// This tells us the page number of the last page
$last = ceil($count/$rpp);
// This makes sure $last cannot be less than 1
if($last < 1){
    $last = 1;
}
// Define pagination control
//$paginationCtrls = "";
// Define page number
$pn = "1";

// Get pagenum from URL vars if it is present, else it is = 1
if(isset($_GET['pn'])){
$pn = preg_replace('#[^0-9]#', '', $_GET['pn']);
$tag = lcfirst(($_GET['tag']));
$id = ($_GET['id']);
//$searchquery = $_POST['searchquery'];
}

// Make the script run only if there is a page number posted to this script

// This makes sure the page number isn't below 1, or more than our $last page
if ($pn < 1) {
    $pn = 1;
} else if ($pn > $last) {
$pn = $last;
}

// This sets the range of rows to query for the chosen $pn
$limit = 'LIMIT ' .($pn - 1) * $rpp .',' .$rpp;

// This is the query again, it is for grabbing just one page worth of rows by applying $limit
$sql = "$sql_statement"." $limit";
$stmt = $db_connect->prepare($sql);
$stmt->bindParam(':id', $id, PDO::PARAM_STR);
$stmt->bindParam(':tag', $tag, PDO::PARAM_STR);
$stmt->execute();

// Establish the $paginationCtrls variable
$paginationCtrls = '';
$resultpage = '';


if($count > 0){
    //$resultpage .= "";
    $resultpage .= "<hr />$count successful request for this broadcast<hr /><br />";
    $resultpage .= "<table style='width:100%; border: 1px solid gray;'>";
    $resultpage .= "<thead style='border: 1px solid gray;'>";
    $resultpage .= "<tr>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Date</th>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Recepient</th>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Duration(msec)</th>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Status</th>";
    $resultpage .= "</tr>";
    $resultpage .= "</thead>";
    $paginationCtrls .= '<div id="paginationctrls">';
    if($last != 1){
        /* First we check if we are on page one. If we are then we don't need a link to
           the previous page or the first page so we do nothing. If we aren't then we
           generate links to the first page, and to the previous page. */
        if ($pn > 1) {
            $previous = $pn - 1;
            $paginationCtrls .= '<a href="'.$_SERVER['PHP_SELF'].'?pn='.$previous.'&id='.$id.'&tag='.$tag.'">Previous</a> &nbsp; &nbsp; ';
            // Render clickable number links that should appear on the left of the target page number
            for($i = $pn-4; $i < $pn; $i++){
                if($i > 0){
                    $paginationCtrls .= '<a href="'.$_SERVER['PHP_SELF'].'?pn='.$i.'&id='.$id.'&tag='.$tag.'">'.$i.'</a> &nbsp; ';
                }
            }
        }
        // Render the target page number, but without it being a link
        $paginationCtrls .= ''.$pn.' &nbsp; ';
        // Render clickable number links that should appear on the right of the target page number
        for($i = $pn+1; $i <= $last; $i++){
            $paginationCtrls .= '<a href="'.$_SERVER['PHP_SELF'].'?pn='.$i.'&id='.$id.'&tag='.$tag.'">'.$i.'</a> &nbsp; ';
            if($i >= $pn+4){
                break;
            }
        }
        // This does the same as above, only checking if we are on the last page, and then generating the "Next"
        if ($pn != $last) {
            $next = $pn + 1;
            $paginationCtrls .= ' &nbsp; &nbsp; <a href="'.$_SERVER['PHP_SELF'].'?pn='.$next.'&id='.$id.'&tag='.$tag.'">Next</a> ';
        }
    }
    $paginationCtrls .= '</div>';

    foreach($stmt->fetchAll(PDO::FETCH_ASSOC) as $row) {
        $talktime = $row['talk'];
        $statuscode = $row['statusCode'];
        $recepient = $row['mobile'];
        $timeofcall = $row['dates'];
        // Strip off part of the recepient
        $rec_mobile = substr($recepient,6);

        $resultpage .= "<tbody>";
        $resultpage .= "<tr>";
            $resultpage .= "<td style='text-align:center; border: 1px solid gray; color:gray;'>" . $timeofcall . "</td>";
            $resultpage .= "<td style='text-align:center; border: 1px solid gray; color:gray;'>" . $recepient . "</td>";
            $resultpage .= "<td style='text-align:center; border: 1px solid gray; color:gray;'>" . $talktime . "</td>";
            $resultpage .= "<td style='text-align:center; border: 1px solid gray; color:gray;'>" . $statuscode . "</td>";
        $resultpage .= "</tr>";
        $resultpage .= "</tbody>";
    }
    $resultpage .= "</table>";

} else {
    $resultpage .= "<table style='width:100%; border: 1px solid gray;'>";
    $resultpage .= "<thead style='border: 1px solid gray;'>";
    $resultpage .= "<tr>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Date</th>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Recepient</th>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Duration(msec)</th>";
        $resultpage .= "<th width='25%'; style='border: 1px solid gray; color:gray;'>Status</th>";
    $resultpage .= "</tr>";
    $resultpage .= "</thead>";
    $resultpage .= "</table>";
    $resultpage .= "<br />";
    $resultpage .= "<hr />0 results for this broadcast<hr />";
}
echo $paginationCtrls;
echo '<br>';
echo '<span style="background-color:grey; color:white; min-width:80px; height:20px;">Amount generated by all my broadcast: '.'<b>'.$amountDue. ' Naira'.'</b></span><br /><br>';
echo '<span style="background-color:grey; color:white; min-width:80px; height:20px;">Amount generated by this broadcast: '.'<b>'.$totalGenerated.' Naira'.'</b></span><br /><br />';
echo '<br>';
echo $resultpage;
?>
